base_packages:
  pacman:
    - fzf
    - ttf-jetbrains-mono-nerd
    - zellij
    - yazi
    - zoxide
    - libnotify
    - notification-daemon
    - swaync
    - networkmanager
    - network-manager-applet
    - pavucontrol
    - bluez
    - bluez-utils
    - blueman
    - chezmoi
    - github-cli
    - wl-clipboard
    - docker
    - docker-compose
    - starship
    - dotnet-sdk
    - polkit-gnome
    - gnome-keyring
    - seahorse
    - gtk3
    - libappindicator-gtk3
    - xdg-desktop-portal
    - xdg-desktop-portal-hyprland
    - ffmpeg
    - p7zip
    - jq
    - poppler
    - fd
    - ripgrep
    - imagemagick
    - zip
    - unzip
    - unixodbc
    - hyprland
    - hyprpaper
    - hyprlock
    - hypridle
    - noto-fonts
    - libnotify
    - dunst
    - kitty
    - qt5-wayland
    - qt6-wayland
    - wget
    - qt5-graphicaleffects
    - qt5-quickcontrols2
    - qt5-svg
    - fastfetch
    - xdg-desktop-portal-gtk
    - eza
    - python-pip
    - python-gobject
    - python-screeninfo
    - tumbler
    - brightnessctl
    - nm-connection-editor
    - gtk4
    - libadwaita
    - fuse2
    - firefox
    - neovim
    - htop
    - nautilus
    - python-pywal
    - grim
    - slurp
    - cliphist
    - nwg-look
    - qt6ct
    - waybar
    - rofi-wayland
    - zsh
    - pavucontrol
    - papirus-icon-theme
    - breeze
    - gvfs
    - otf-font-awesome
    - ttf-fira-sans
    - ttf-fira-code
    - ttf-firacode-nerd
    - nwg-dock-hyprland

  aur:
    simple:
      - oh-my-posh-bin
      - xclip-git
      - jetbrains-toolbox
      - ghostty
      - visual-studio-code-bin
      - microsoft-edge-stable
      - pulumi
      - anydesk-bin
      - zsh-autosuggestions
      - zsh-syntax-highlighting
      - zsh-fast-syntax-highlighting
      - zsh-completions
      - hypridle
      - hyprlock
      - hyprpaper
      - nautilus-open-any-termina
      - aylurs-gtk-shell
      - bibata-cursor-theme-bin
      - checkupdates-with-aur
      - grimblast-git
      - hyprshade
      - mission-center
      - nautilus-open-any-terminal
      - pacseek
      - pinta
      - python-pywalfox
      - python-screeninfo
      - smile
      - waypaper
      - wlogout
      - zen-browser-bin

    interactive:
      - name: slack-desktop
        description: "Slack Desktop (multiple versions available)"
      - name: asdf-vm
        description: "ASDF Version Manager (multiple versions available)"

post_install_actions:
  directories:
    - type: directories
      paths:
        - path: ~/.1password/ssh
          mode: "700"
        - path: ~/.ssh
          mode: "700"
        - path: ~/.config/1Password
        - path: ~/.local/share/1Password
      description: Create required directories with proper permissions

  1password:
    - type: gpg_import
      url: https://downloads.1password.com/linux/keys/1password.asc
      description: Import 1Password GPG key
    - type: package
      name: 1password
      method: paru
      description: Install 1Password
    - type: symlinks
      links:
        - source: /opt/1Password/com.1password.1password.json
          target: /etc/opt/chrome/native-messaging-hosts/com.1password.1password.json
          sudo: true
        - source: /opt/1Password/com.1password.1password.json
          target: /etc/chromium/native-messaging-hosts/com.1password.1password.json
          sudo: true
      description: Setup browser integration for 1Password

  atuin:
    - type: curl
      url: https://setup.atuin.sh
      pipe_to: sh
      description: Install Atuin shell history sync

  browser:
    - type: command
      cmd: xdg-settings
      args:
        - set
        - default-web-browser
        - microsoft-edge.desktop
      description: Set default browser

  git:
    - type: git_config
      settings:
        - key: alias.acp
          value: |
            !f() {
              git add .;
              echo "Enter commit message:";
              read -r msg;
              git commit -m "$msg";
              echo "Pushing changes...";
              git push origin "$(git symbolic-ref --short HEAD)";
              }; f
        - key: user.email
          value: luiz.rocha@coelhorocha.com
        - key: user.name
          value: Luiz Rocha
      description: Configure git settings

  zsh:
    - type: command
      cmd: chsh
      args:
        - -s
        - /usr/bin/zsh
      description: Changes shell to zsh

  slack-cli:
    - type: command
      cmd: sudo
      args:
        - chown
        - -R
        - $USER:$USER
        - /usr/local/bin
      description: Fix permissions for local bin
    - type: curl
      url: https://downloads.slack-edge.com/slack-cli/install.sh
      pipe_to: bash -s slack-cli
      description: Install Slack CLI

  docker:
    - type: systemd
      actions:
        - service: docker.service
          operations:
        - enable
        - start
    - type: command
      cmd: sudo
      args:
        - usermod
        - -aG
        - docker
        - $USER
      description: Add user to docker group

  bluetooth:
    - type: systemd
      actions:
        - service: bluetooth.service
          operations:
            - enable
            - start

  NetworkManager:
    - type: systemd
      actions:
        - service: NetworkManager.service
          operations:
            - enable
            - start

  asdf-vm:
    - type: command
      cmd: bash
      args:
        - -c
        - source /opt/asdf-vm/asdf.sh && asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git && asdf install nodejs latest
      description: Setup ASDF and install Node.js
