# Package definitions and post-installation actions
base_packages:
  pacman:
    - fzf
    - ttf-jetbrains-mono-nerd
    - zellij
    - yazi
    - zoxide
    - libnotify
    - notification-daemon
    - swaync
    - networkmanager
    - network-manager-applet
    - pavucontrol
    - bluez
    - bluez-utils
    - blueman
    - chezmoi
    - github-cli
    - docker
    - docker-compose
    - starship
    - dotnet-sdk

  aur:
    - oh-my-posh-bin
    - xclip-git
    - slack-desktop
    - jetbrains-toolbox
    - ghostty
    - visual-studio-code-bin
    - microsoft-edge-stable
    - pulumi
    - asdf-vm
    - anydesk-bin
    - zsh-autosuggestions
    - zsh-syntax-highlighting
    - zsh-fast-syntax-highlighting

post_install_actions:
  atuin:
    - command: curl --proto '=https' --tlsv1.2 -LsSf https://setup.atuin.sh | sh
  browser:
    - command: xdg-settings set default-web-browser microsoft-edge.desktop
  git:
    - command: git config --global alias.acp '!f() { git add .; echo %%Enter commit message:%%; read -r msg; git commit -m %%$msg%%; echo %%Pushing changes...%%; git push origin %%$(git symbolic-ref --short HEAD)%%; }; f'
    - command: git config --global user.email %%luiz.rocha@coelhorocha.com%%
    - command: git config --global user.name %%Luiz Rocha%%
  1password:
    - command: curl -sS https://downloads.1password.com/linux/keys/1password.asc | gpg --import
    - command: paru -Sy --needed 1password
  slack-cli:
    - command: sudo chown -R $USER:$USER /usr/local/bin
    - command: curl -fsSL https://downloads.slack-edge.com/slack-cli/install.sh | bash -s slack-cli
  dagger:
    - command: curl -fsSL https://dl.dagger.io/dagger/install.sh | BIN_DIR=$HOME/.local/bin sh
  docker:
    - command: sudo systemctl enable docker.service
    - command: sudo systemctl start docker.service
    - command: sudo usermod -aG docker $USER
  bluetooth:
    - command: systemctl enable bluetooth.service
    - command: systemctl start bluetooth.service
  NetworkManager:
    - command: systemctl enable NetworkManager.service
    - command: systemctl start NetworkManager.service
  asdf-vm:
    - command: source /opt/asdf-vm/asdf.sh && asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git && asdf install nodejs latest
